#!/bin/bash

build/point_sprite_test --graphics-screen-size='(1024,768)' --camera-roll-speed=0.7 --camera-speed=100 --camera-near=1 --camera-far=1000 --camera-fov=90 --texture=/home/philipp/projects/insula/media/particle.png --point-count=1000 
